#pragma once

typedef __int16(__cdecl *hs_script_op_callback)(int, int, char);
enum class hs_value_type : unsigned __int16
{
	k_hs_value_type_invalid = 0xBABA,
	k_hs_value_type_unparsed = 0x0,
	k_hs_value_type_special_form = 0x1,
	k_hs_value_type_function_name = 0x2,
	k_hs_value_type_passthrough = 0x3,
	k_hs_value_type_void = 0x4,
	k_hs_value_type_boolean = 0x5,
	k_hs_value_type_real = 0x6,
	k_hs_value_type_short = 0x7,
	k_hs_value_type_long = 0x8,
	k_hs_value_type_string = 0x9,
	k_hs_value_type_script = 0xA,
	k_hs_value_type_string_id = 0xB,
	k_hs_value_type_unit_seat_mapping = 0xC,
	k_hs_value_type_trigger_volume = 0xD,
	k_hs_value_type_cutscene_flag = 0xE,
	k_hs_value_type_cutscene_camera_point = 0xF,
	k_hs_value_type_cutscene_title = 0x10,
	k_hs_value_type_cutscene_recording = 0x11,
	k_hs_value_type_device_group = 0x12,
	k_hs_value_type_ai = 0x13,
	k_hs_value_type_ai_command_list = 0x14,
	k_hs_value_type_ai_command_script = 0x15,
	k_hs_value_type_ai_behavior = 0x16,
	k_hs_value_type_ai_orders = 0x17,
	k_hs_value_type_ai_line = 0x18,
	k_hs_value_type_starting_profile = 0x19,
	k_hs_value_type_conversation = 0x1A,
	k_hs_value_type_zone_set = 0x1B,
	k_hs_value_type_designer_zone = 0x1C,
	k_hs_value_type_point_reference = 0x1D,
	k_hs_value_type_style = 0x1E,
	k_hs_value_type_object_list = 0x1F,
	k_hs_value_type_folder = 0x20,
	k_hs_value_type_sound = 0x21,
	k_hs_value_type_effect = 0x22,
	k_hs_value_type_damage = 0x23,
	k_hs_value_type_looping_sound = 0x24,
	k_hs_value_type_animation_graph = 0x25,
	k_hs_value_type_damage_effect = 0x26,
	k_hs_value_type_object_definition = 0x27,
	k_hs_value_type_bitmap = 0x28,
	k_hs_value_type_shader = 0x29,
	k_hs_value_type_render_model = 0x2A,
	k_hs_value_type_structure_definition = 0x2B,
	k_hs_value_type_lightmap_definition = 0x2C,
	k_hs_value_type_cinematic_definition = 0x2D,
	k_hs_value_type_cinematic_scene_definition = 0x2E,
	k_hs_value_type_bink_definition = 0x2F,
	k_hs_value_type_any_tag = 0x30,
	k_hs_value_type_any_tag_not_resolving = 0x31,
	k_hs_value_type_game_difficulty = 0x32,
	k_hs_value_type_team = 0x33,
	k_hs_value_type_mp_team = 0x34,
	k_hs_value_type_controller = 0x35,
	k_hs_value_type_button_preset = 0x36,
	k_hs_value_type_joystick_preset = 0x37, //<!--honline does not have "player_color" -->
	k_hs_value_type_player_character_type = 0x38,
	k_hs_value_type_voice_output_setting = 0x39,
	k_hs_value_type_voice_mask = 0x3A,
	k_hs_value_type_subtitle_setting = 0x3B,
	k_hs_value_type_actor_type = 0x3C,
	k_hs_value_type_model_state = 0x3D,
	k_hs_value_type_event = 0x3E,
	k_hs_value_type_character_physics = 0x3F,
	k_hs_value_type_primary_skull = 0x40,
	k_hs_value_type_secondary_skull = 0x41,
	k_hs_value_type_object = 0x42,
	k_hs_value_type_unit = 0x43,
	k_hs_value_type_vehicle = 0x44,
	k_hs_value_type_weapon = 0x45,
	k_hs_value_type_device = 0x46,
	k_hs_value_type_scenery = 0x47,
	k_hs_value_type_effect_scenery = 0x48,
	k_hs_value_type_object_name = 0x49,
	k_hs_value_type_unit_name = 0x4A,
	k_hs_value_type_vehicle_name = 0x4B,
	k_hs_value_type_weapon_name = 0x4C,
	k_hs_value_type_device_name = 0x4D,
	k_hs_value_type_scenery_name = 0x4E,
	k_hs_value_type_effect_scenery_name = 0x4F,
	k_hs_value_type_cinematic_lightprobe = 0x50,
	k_hs_value_type_animation_budget_reference = 0x51,
	k_hs_value_type_looping_sound_budget_reference = 0x52,
	k_hs_value_type_sound_budget_reference = 0x53,
};

struct hs_function_definition
{
	hs_value_type return_type;
	__int16 unknown1;
	hs_script_op_callback callback;
	const char *usage;
	int unknown2;
	hs_value_type parameters[16];
};